using mototun.Core.Interfaces;
using mototun.Core.Entities;
using mototun.Core.Enums;
using mototun.Infrastructure.Data;
using mototun.Infrastructure.Services;
using mototun.API.Services.Email;
using mototun.API.Services.DocumentAnalysis;
using mototun.API.Services.Invoices;
using mototun.API.Services.InvoicePdf;
using mototun.API.Services.Reminders;
using mototun.API.Services.Security;
using mototun.API.Services.Storage;
using mototun.API.Extensions;
using mototun.API.Security;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.AspNetCore.HttpLogging;
using Microsoft.AspNetCore.HttpOverrides;
using Microsoft.AspNetCore.RateLimiting;
using Microsoft.AspNetCore.ResponseCompression;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.FileProviders;
using Microsoft.Extensions.Options;
using Microsoft.IdentityModel.Tokens;
using Microsoft.OpenApi.Models;
using System.IO.Compression;
using System.Security.Claims;
using System.Security.Cryptography;
using System.Text;
using System.Threading.RateLimiting;

var builder = WebApplication.CreateBuilder(args);
PreferredEnvironmentVariableAliases.Apply(builder.Configuration);

builder.Services.AddControllers()
    .AddJsonOptions(options =>
    {
        options.JsonSerializerOptions.ReferenceHandler = System.Text.Json.Serialization.ReferenceHandler.IgnoreCycles;
        options.JsonSerializerOptions.DefaultIgnoreCondition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull;
    });

builder.Services.AddEndpointsApiExplorer();
builder.Services.AddExceptionHandler<GlobalExceptionHandler>();
builder.Services.AddProblemDetails();
builder.Services.AddHttpLogging(options =>
{
    options.LoggingFields = HttpLoggingFields.RequestMethod
        | HttpLoggingFields.RequestPath
        | HttpLoggingFields.ResponseStatusCode
        | HttpLoggingFields.Duration;
});
builder.Services.Configure<ForwardedHeadersOptions>(options =>
{
    options.ForwardedHeaders = ForwardedHeaders.XForwardedFor | ForwardedHeaders.XForwardedProto;
    options.KnownNetworks.Clear();
    options.KnownProxies.Clear();
});

builder.Services.AddSwaggerGen(options =>
{
    options.SwaggerDoc("v1", new OpenApiInfo
    {
        Title = "Mototun Management API",
        Version = "v1"
    });

    options.AddSecurityDefinition("Bearer", new OpenApiSecurityScheme
    {
        Description = "JWT Authorization header using the Bearer scheme. Enter 'Bearer' [space] and then your token",
        Name = "Authorization",
        In = ParameterLocation.Header,
        Type = SecuritySchemeType.ApiKey,
        Scheme = "Bearer"
    });

    options.AddSecurityRequirement(new OpenApiSecurityRequirement
    {
        {
            new OpenApiSecurityScheme
            {
                Reference = new OpenApiReference
                {
                    Type = ReferenceType.SecurityScheme,
                    Id = "Bearer"
                }
            },
            Array.Empty<string>()
        }
    });
});

ConfigureDatabase(
    builder.Configuration,
    builder.Environment,
    builder.Services,
    out var usingInMemoryDatabaseFallback,
    out var databaseFallbackReason);

var jwtSettings = builder.Configuration.GetSection("JwtSettings");
var autoGeneratedJwtSecret = false;
var secretKey = ResolveJwtSecretKey(builder.Configuration, builder.Environment, out autoGeneratedJwtSecret);
builder.Configuration["JwtSettings:SecretKey"] = secretKey;

builder.Services.AddAuthentication("Bearer")
    .AddJwtBearer(options =>
    {
        options.TokenValidationParameters = new TokenValidationParameters
        {
            ValidateIssuer = true,
            ValidateAudience = true,
            ValidateLifetime = true,
            ValidateIssuerSigningKey = true,
            RequireExpirationTime = true,
            ClockSkew = TimeSpan.FromSeconds(30),
            ValidIssuer = jwtSettings["Issuer"],
            ValidAudience = jwtSettings["Audience"],
            IssuerSigningKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(secretKey))
        };
        options.Events = new JwtBearerEvents
        {
            OnMessageReceived = context =>
            {
                if (string.IsNullOrWhiteSpace(context.Token)
                    && context.Request.Cookies.TryGetValue(AuthCookieDefaults.CookieName, out var cookieToken))
                {
                    context.Token = cookieToken;
                }

                return Task.CompletedTask;
            },
            OnTokenValidated = async context =>
            {
                var userIdValue = context.Principal?.FindFirstValue(ClaimTypes.NameIdentifier);
                if (!int.TryParse(userIdValue, out var userId))
                {
                    context.Fail("Invalid session.");
                    return;
                }

                var dbContext = context.HttpContext.RequestServices.GetRequiredService<ApplicationDbContext>();
                var currentUser = await dbContext.Users
                    .AsNoTracking()
                    .Where(user => user.Id == userId)
                    .Select(user => new
                    {
                        user.Status,
                        user.CanLogin
                    })
                    .FirstOrDefaultAsync(context.HttpContext.RequestAborted);

                if (currentUser is null
                    || currentUser.Status != UserStatus.Active
                    || !currentUser.CanLogin)
                {
                    context.Fail("User account is no longer allowed to access this resource.");
                }
            }
        };
    });

builder.Services.AddAuthorization();
builder.Services.AddRateLimiter(options =>
{
    options.RejectionStatusCode = StatusCodes.Status429TooManyRequests;
    options.OnRejected = async (context, cancellationToken) =>
    {
        context.HttpContext.Response.ContentType = "application/json";
        await context.HttpContext.Response.WriteAsJsonAsync(new
        {
            success = false,
            message = "Too many requests. Please try again later."
        }, cancellationToken);
    };

    options.AddPolicy("AuthLogin", httpContext =>
        RateLimitPartition.GetFixedWindowLimiter(
            partitionKey: $"{GetClientIpPartitionKey(httpContext)}::login",
            factory: _ => new FixedWindowRateLimiterOptions
            {
                PermitLimit = 5,
                Window = TimeSpan.FromMinutes(1),
                QueueLimit = 0
            }));

    options.AddPolicy("AuthRegister", httpContext =>
        RateLimitPartition.GetFixedWindowLimiter(
            partitionKey: $"{GetClientIpPartitionKey(httpContext)}::register",
            factory: _ => new FixedWindowRateLimiterOptions
            {
                PermitLimit = 3,
                Window = TimeSpan.FromMinutes(10),
                QueueLimit = 0
            }));

    options.AddPolicy("AuthLookup", httpContext =>
        RateLimitPartition.GetFixedWindowLimiter(
            partitionKey: $"{GetClientIpPartitionKey(httpContext)}::lookup",
            factory: _ => new FixedWindowRateLimiterOptions
            {
                PermitLimit = 20,
                Window = TimeSpan.FromMinutes(1),
                QueueLimit = 0
            }));

    options.AddPolicy("AuthForgotPassword", httpContext =>
        RateLimitPartition.GetFixedWindowLimiter(
            partitionKey: $"{GetClientIpPartitionKey(httpContext)}::forgot-password",
            factory: _ => new FixedWindowRateLimiterOptions
            {
                PermitLimit = 5,
                Window = TimeSpan.FromMinutes(10),
                QueueLimit = 0
            }));

    options.AddPolicy("AuthResetPassword", httpContext =>
        RateLimitPartition.GetFixedWindowLimiter(
            partitionKey: $"{GetClientIpPartitionKey(httpContext)}::reset-password",
            factory: _ => new FixedWindowRateLimiterOptions
            {
                PermitLimit = 10,
                Window = TimeSpan.FromMinutes(10),
                QueueLimit = 0
            }));

    options.AddPolicy("AuthRead", httpContext =>
        RateLimitPartition.GetFixedWindowLimiter(
            partitionKey: $"{GetClientIpPartitionKey(httpContext)}::read",
            factory: _ => new FixedWindowRateLimiterOptions
            {
                PermitLimit = 60,
                Window = TimeSpan.FromMinutes(1),
                QueueLimit = 0
            }));

    options.AddPolicy("AuthWrite", httpContext =>
        RateLimitPartition.GetFixedWindowLimiter(
            partitionKey: $"{GetClientIpPartitionKey(httpContext)}::write",
            factory: _ => new FixedWindowRateLimiterOptions
            {
                PermitLimit = 20,
                Window = TimeSpan.FromMinutes(1),
                QueueLimit = 0
            }));

    options.AddPolicy("ClientPortalAccess", httpContext =>
        RateLimitPartition.GetFixedWindowLimiter(
            partitionKey: $"{GetClientIpPartitionKey(httpContext)}::portal-access",
            factory: _ => new FixedWindowRateLimiterOptions
            {
                PermitLimit = 10,
                Window = TimeSpan.FromMinutes(5),
                QueueLimit = 0
            }));

    options.AddPolicy("ClientPortalRead", httpContext =>
        RateLimitPartition.GetFixedWindowLimiter(
            partitionKey: $"{GetClientIpPartitionKey(httpContext)}::portal-read",
            factory: _ => new FixedWindowRateLimiterOptions
            {
                PermitLimit = 30,
                Window = TimeSpan.FromMinutes(1),
                QueueLimit = 0
            }));
});

var configuredCorsOrigins = LoadCorsAllowedOrigins(builder.Configuration);
if (!builder.Environment.IsDevelopment())
{
    ProductionConfigurationValidator.ValidateNonDevelopmentConfiguration(builder.Configuration, configuredCorsOrigins);
}

builder.Services.AddCors(options =>
{
    options.AddPolicy("AllowFrontend", policy =>
    {
        policy.SetIsOriginAllowed(origin =>
              IsAllowedCorsOrigin(origin, configuredCorsOrigins, builder.Environment.IsDevelopment()))
              .AllowAnyHeader()
              .AllowAnyMethod()
              .AllowCredentials();
    });
});

builder.Services.AddResponseCompression(options =>
{
    options.EnableForHttps = true;
    options.Providers.Add<BrotliCompressionProvider>();
    options.Providers.Add<GzipCompressionProvider>();
});
builder.Services.Configure<BrotliCompressionProviderOptions>(options =>
{
    options.Level = CompressionLevel.Fastest;
});
builder.Services.Configure<GzipCompressionProviderOptions>(options =>
{
    options.Level = CompressionLevel.Fastest;
});

builder.Services.AddScoped<IAuthService, AuthService>();
builder.Services.AddScoped<IInvoiceSettingsService, InvoiceSettingsService>();
builder.Services.Configure<CloudflareTurnstileOptions>(builder.Configuration.GetSection(CloudflareTurnstileOptions.SectionName));
builder.Services.AddHttpClient<ITurnstileValidationService, CloudflareTurnstileValidationService>(client =>
{
    client.Timeout = TimeSpan.FromSeconds(10);
});
builder.Services.AddOptions<ResendOptions>()
    .Configure<IConfiguration>((options, configuration) => ResendOptionsResolver.Bind(configuration, options));
builder.Services.AddSingleton<IEmailTemplateRenderer, FileEmailTemplateRenderer>();
builder.Services.AddScoped<IApplicationEmailService, ApplicationEmailService>();
builder.Services.AddHttpClient<IEmailSender, ResendEmailSender>(client =>
{
    client.Timeout = TimeSpan.FromSeconds(15);
});
builder.Services.Configure<DocumentOcrOptions>(builder.Configuration.GetSection(DocumentOcrOptions.SectionName));
builder.Services.Configure<InvoicePdfOptions>(builder.Configuration.GetSection(InvoicePdfOptions.SectionName));
builder.Services.Configure<StuckDossierReminderOptions>(builder.Configuration.GetSection(StuckDossierReminderOptions.SectionName));
builder.Services.Configure<AzureBlobOptions>(builder.Configuration.GetSection(AzureBlobOptions.SectionName));
builder.Services.AddHttpClient();
builder.Services.AddScoped<IDocumentAutoValidationService, PaddleOcrDocumentAutoValidationService>();
builder.Services.AddScoped<IInvoiceDashboardService, InvoiceDashboardService>();
builder.Services.AddSingleton<LocalFileStorage>();
builder.Services.AddSingleton<AzureBlobFileStorage>();
builder.Services.AddSingleton<IFileStorage>(serviceProvider =>
{
    var options = serviceProvider.GetRequiredService<IOptions<AzureBlobOptions>>().Value;
    return string.IsNullOrWhiteSpace(options.ConnectionString)
        ? serviceProvider.GetRequiredService<LocalFileStorage>()
        : serviceProvider.GetRequiredService<AzureBlobFileStorage>();
});
builder.Services.AddSingleton<LocalAvatarStorage>();
builder.Services.AddSingleton<AzureBlobAvatarStorage>();
builder.Services.AddSingleton<BlobPreferredAvatarStorage>();
builder.Services.AddSingleton<IAvatarStorage>(serviceProvider =>
{
    var options = serviceProvider.GetRequiredService<IOptions<AzureBlobOptions>>().Value;
    return string.IsNullOrWhiteSpace(options.ConnectionString)
        ? serviceProvider.GetRequiredService<LocalAvatarStorage>()
        : serviceProvider.GetRequiredService<BlobPreferredAvatarStorage>();
});
builder.Services.AddSingleton<FileInvoicePdfSettingsStore>();
builder.Services.AddSingleton<BlobInvoicePdfSettingsStore>();
builder.Services.AddSingleton<IInvoicePdfSettingsStore>(serviceProvider =>
{
    var options = serviceProvider.GetRequiredService<IOptions<AzureBlobOptions>>().Value;
    return string.IsNullOrWhiteSpace(options.ConnectionString)
        ? serviceProvider.GetRequiredService<FileInvoicePdfSettingsStore>()
        : serviceProvider.GetRequiredService<BlobInvoicePdfSettingsStore>();
});
builder.Services.AddScoped<IStuckDossierReminderDispatcher, StuckDossierReminderDispatcher>();
builder.Services.AddHostedService<StuckDossierReminderHostedService>();

var app = builder.Build();
var embeddablePreviewFrameAncestors = BuildEmbeddablePreviewFrameAncestors(configuredCorsOrigins, app.Environment.IsDevelopment());
if (usingInMemoryDatabaseFallback)
{
    app.Logger.LogWarning(
        "SQL Server is unavailable. Falling back to in-memory development database. Data is not persisted. Reason: {Reason}",
        databaseFallbackReason ?? "Unknown");
}
if (autoGeneratedJwtSecret)
{
    app.Logger.LogWarning("JwtSettings:SecretKey is missing. Generated an ephemeral development secret for this process.");
}
var configuredUrls = builder.Configuration["ASPNETCORE_URLS"] ?? string.Empty;
var hasHttpsEndpoint = configuredUrls
    .Split(';', StringSplitOptions.RemoveEmptyEntries)
    .Any(url => url.TrimStart().StartsWith("https://", StringComparison.OrdinalIgnoreCase));

if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI();
}
else
{
    app.UseHsts();
}

app.UseForwardedHeaders();
app.UseExceptionHandler();

if (hasHttpsEndpoint)
{
    app.UseHttpsRedirection();
}

app.UseHttpLogging();
app.UseResponseCompression();

app.Use(async (context, next) =>
{
    context.Response.Headers["X-Content-Type-Options"] = "nosniff";
    context.Response.Headers["Referrer-Policy"] = "no-referrer";
    context.Response.Headers["Permissions-Policy"] = "geolocation=(), microphone=(), camera=()";

    if (IsEmbeddableDocumentPreviewPath(context.Request.Path))
    {
        context.Response.Headers.Remove("X-Frame-Options");
        context.Response.Headers["Content-Security-Policy"] = embeddablePreviewFrameAncestors;
    }
    else
    {
        context.Response.Headers["X-Frame-Options"] = "DENY";
        context.Response.Headers["Content-Security-Policy"] = "frame-ancestors 'none'";
    }

    if (context.Request.IsHttps)
    {
        context.Response.Headers["Strict-Transport-Security"] = "max-age=31536000; includeSubDomains";
    }

    await next();
});

var storageRootBase = app.Environment.ContentRootPath;
var marker = $"{Path.DirectorySeparatorChar}bin{Path.DirectorySeparatorChar}";
var markerIndex = storageRootBase.IndexOf(marker, StringComparison.OrdinalIgnoreCase);
if (markerIndex > 0)
{
    var projectRoot = storageRootBase[..markerIndex];
    if (Directory.Exists(projectRoot))
    {
        storageRootBase = projectRoot;
    }
}

var storageRoot = Path.Combine(storageRootBase, "Storage");
Directory.CreateDirectory(storageRoot);
var avatarsRoot = Path.Combine(storageRoot, "Avatars");
Directory.CreateDirectory(avatarsRoot);
app.UseStaticFiles(new StaticFileOptions
{
    FileProvider = new PhysicalFileProvider(avatarsRoot),
    RequestPath = "/Storage/Avatars"
});

app.UseCors("AllowFrontend");
app.UseRateLimiter();
app.UseAuthentication();
app.UseAuthorization();
app.MapGet("/health", (IWebHostEnvironment environment) =>
{
    return Results.Ok(new
    {
        status = "ok",
        environment = environment.EnvironmentName,
        database = "unchecked",
        utcTime = DateTime.UtcNow
    });
}).AllowAnonymous();
app.MapGet("/health/ready", async (ApplicationDbContext dbContext, IWebHostEnvironment environment, CancellationToken cancellationToken) =>
{
    var databaseStatus = "ok";
    var isHealthy = true;

    try
    {
        if (dbContext.Database.IsRelational())
        {
            using var readinessTimeout = CancellationTokenSource.CreateLinkedTokenSource(cancellationToken);
            readinessTimeout.CancelAfter(TimeSpan.FromSeconds(5));

            isHealthy = await dbContext.Database.CanConnectAsync(readinessTimeout.Token);
            databaseStatus = isHealthy ? "ok" : "unavailable";
        }
    }
    catch (OperationCanceledException)
    {
        isHealthy = false;
        databaseStatus = "timeout";
    }
    catch
    {
        isHealthy = false;
        databaseStatus = "unavailable";
    }

    var payload = new
    {
        status = isHealthy ? "ok" : "degraded",
        environment = environment.EnvironmentName,
        database = databaseStatus,
        utcTime = DateTime.UtcNow
    };

    return isHealthy
        ? Results.Ok(payload)
        : Results.Json(payload, statusCode: StatusCodes.Status503ServiceUnavailable);
}).AllowAnonymous();
app.MapControllers();

if (app.Environment.IsDevelopment())
{
    await EnsureDatabaseReadyAsync(app.Services, app.Logger);
    await EnsureAdminBootstrapAsync(app.Services, builder.Configuration, app.Logger);
}

app.Run();

static async Task EnsureAdminBootstrapAsync(IServiceProvider services, IConfiguration configuration, ILogger logger)
{
    var bootstrapSection = configuration.GetSection("AdminBootstrap");
    var enabled = bootstrapSection.GetValue<bool>("Enabled");
    if (!enabled)
    {
        return;
    }

    var configuredEmail = bootstrapSection["Email"];
    var password = bootstrapSection["Password"];
    var fullName = bootstrapSection["FullName"]?.Trim();

    if (ConfigurationValueGuards.IsPlaceholder(configuredEmail)
        || ConfigurationValueGuards.IsPlaceholder(password))
    {
        logger.LogWarning("AdminBootstrap uses placeholder values. Set ADMIN_BOOTSTRAP__EMAIL and ADMIN_BOOTSTRAP__PASSWORD environment variables.");
        return;
    }

    if (!ConfigurationValueGuards.HasConfiguredValue(configuredEmail)
        || !ConfigurationValueGuards.HasConfiguredValue(password))
    {
        logger.LogWarning("AdminBootstrap is enabled but Email/Password is missing.");
        return;
    }

    var email = configuredEmail!.Trim().ToLowerInvariant();
    using var scope = services.CreateScope();
    var context = scope.ServiceProvider.GetRequiredService<ApplicationDbContext>();

    var existing = await context.Users.FirstOrDefaultAsync(u => u.Email == email);
    if (existing is not null)
    {
        var needsSave = false;

        if (existing.Role != UserRole.Admin)
        {
            existing.Role = UserRole.Admin;
            existing.Status = UserStatus.Active;
            existing.CanLogin = true;
            existing.UpdatedAt = DateTime.UtcNow;
            needsSave = true;
        }

        if (!BCrypt.Net.BCrypt.Verify(password, existing.PasswordHash))
        {
            existing.PasswordHash = BCrypt.Net.BCrypt.HashPassword(password);
            existing.UpdatedAt = DateTime.UtcNow;
            needsSave = true;
        }

        if (needsSave)
        {
            await context.SaveChangesAsync();
        }

        return;
    }

    var now = DateTime.UtcNow;
    context.Users.Add(new User
    {
        Email = email,
        PasswordHash = BCrypt.Net.BCrypt.HashPassword(password),
        FullName = string.IsNullOrWhiteSpace(fullName) ? "Admin" : fullName,
        Role = UserRole.Admin,
        Status = UserStatus.Active,
        CanLogin = true,
        CreatedAt = now,
        UpdatedAt = now
    });

    await context.SaveChangesAsync();
    logger.LogInformation("Development admin user bootstrapped: {Email}", email);
}

static async Task EnsureDatabaseReadyAsync(IServiceProvider services, ILogger logger)
{
    using var scope = services.CreateScope();
    var context = scope.ServiceProvider.GetRequiredService<ApplicationDbContext>();

    if (!context.Database.IsRelational())
    {
        return;
    }

    try
    {
        await context.Database.MigrateAsync();
    }
    catch (Exception ex)
    {
        logger.LogError(ex, "Database migration failed during startup.");
        throw;
    }
}

static void ConfigureDatabase(
    IConfiguration configuration,
    IWebHostEnvironment environment,
    IServiceCollection services,
    out bool usingInMemoryDatabaseFallback,
    out string? fallbackReason)
{
    var connectionString = configuration.GetConnectionString("DefaultConnection");
    var hasConfiguredConnectionString = ConfigurationValueGuards.HasConfiguredValue(connectionString);
    var fallbackEnabled = environment.IsDevelopment()
        && configuration.GetValue("Database:EnableInMemoryFallback", false);
    var probeTimeoutSeconds = Math.Max(1, configuration.GetValue("Database:ConnectionProbeTimeoutSeconds", 3));

    if (fallbackEnabled
        && !CanConnectToSqlServer(connectionString, probeTimeoutSeconds, out fallbackReason))
    {
        var databaseName = configuration["Database:InMemoryDatabaseName"]?.Trim();
        if (string.IsNullOrWhiteSpace(databaseName))
        {
            databaseName = "mototun-dev";
        }

        services.AddDbContext<ApplicationDbContext>(options =>
            options.UseInMemoryDatabase(databaseName));
        usingInMemoryDatabaseFallback = true;
        return;
    }

    if (!hasConfiguredConnectionString)
    {
        throw new InvalidOperationException("ConnectionStrings:DefaultConnection is not configured.");
    }

    services.AddDbContext<ApplicationDbContext>(options =>
        options.UseSqlServer(connectionString));
    usingInMemoryDatabaseFallback = false;
    fallbackReason = null;
}

static bool CanConnectToSqlServer(string? connectionString, int timeoutSeconds, out string? failureReason)
{
    if (!ConfigurationValueGuards.HasConfiguredValue(connectionString))
    {
        failureReason = "Connection string is missing.";
        return false;
    }

    try
    {
        var builder = new SqlConnectionStringBuilder(connectionString)
        {
            ConnectTimeout = timeoutSeconds
        };

        using var connection = new SqlConnection(builder.ConnectionString);
        connection.Open();
        failureReason = null;
        return true;
    }
    catch (Exception ex)
    {
        failureReason = ex.Message;
        return false;
    }
}

static string GetClientIpPartitionKey(HttpContext httpContext)
{
    return httpContext.Connection.RemoteIpAddress?.ToString() ?? "unknown";
}

static HashSet<string> LoadCorsAllowedOrigins(IConfiguration configuration)
{
    var configuredOrigins = configuration.GetSection("Cors:AllowedOrigins").Get<string[]>() ?? Array.Empty<string>();
    var normalizedOrigins = new HashSet<string>(StringComparer.OrdinalIgnoreCase);

    foreach (var origin in configuredOrigins)
    {
        var normalizedOrigin = NormalizeCorsOrigin(origin);
        if (!string.IsNullOrWhiteSpace(normalizedOrigin))
        {
            normalizedOrigins.Add(normalizedOrigin);
        }
    }

    return normalizedOrigins;
}

static bool IsAllowedCorsOrigin(string origin, HashSet<string> configuredOrigins, bool isDevelopment)
{
    var normalizedOrigin = NormalizeCorsOrigin(origin);
    if (string.IsNullOrWhiteSpace(normalizedOrigin))
    {
        return false;
    }

    if (configuredOrigins.Contains(normalizedOrigin))
    {
        return true;
    }

    if (!isDevelopment || !Uri.TryCreate(normalizedOrigin, UriKind.Absolute, out var uri))
    {
        return false;
    }

    return uri.IsLoopback || uri.Host.Equals("localhost", StringComparison.OrdinalIgnoreCase);
}

static string BuildEmbeddablePreviewFrameAncestors(HashSet<string> configuredOrigins, bool isDevelopment)
{
    var allowedOrigins = configuredOrigins
        .Where(origin => !string.IsNullOrWhiteSpace(origin))
        .Distinct(StringComparer.OrdinalIgnoreCase)
        .ToList();

    if (isDevelopment)
    {
        foreach (var developmentOrigin in new[] { "http://localhost:5173", "http://127.0.0.1:5173" })
        {
            if (!allowedOrigins.Contains(developmentOrigin, StringComparer.OrdinalIgnoreCase))
            {
                allowedOrigins.Add(developmentOrigin);
            }
        }
    }

    return allowedOrigins.Count == 0
        ? "frame-ancestors 'self'"
        : $"frame-ancestors 'self' {string.Join(' ', allowedOrigins)}";
}

static bool IsEmbeddableDocumentPreviewPath(PathString path)
{
    if (!path.HasValue)
    {
        return false;
    }

    var value = path.Value ?? string.Empty;
    if (!value.EndsWith("/inline", StringComparison.OrdinalIgnoreCase))
    {
        return false;
    }

    return value.StartsWith("/api/Invoices/", StringComparison.OrdinalIgnoreCase)
        || value.StartsWith("/api/client-portal/", StringComparison.OrdinalIgnoreCase);
}

static string? NormalizeCorsOrigin(string? origin)
{
    if (string.IsNullOrWhiteSpace(origin))
    {
        return null;
    }

    if (!Uri.TryCreate(origin.Trim(), UriKind.Absolute, out var uri))
    {
        return null;
    }

    if (uri.Scheme != Uri.UriSchemeHttp && uri.Scheme != Uri.UriSchemeHttps)
    {
        return null;
    }

    return uri.GetLeftPart(UriPartial.Authority).TrimEnd('/');
}

static string ResolveJwtSecretKey(IConfiguration configuration, IWebHostEnvironment environment, out bool wasAutoGenerated)
{
    var configuredSecret = configuration["JwtSettings:SecretKey"]?.Trim();
    if (ConfigurationValueGuards.HasConfiguredValue(configuredSecret))
    {
        ValidateJwtSecret(configuredSecret!);
        wasAutoGenerated = false;
        return configuredSecret!;
    }

    if (!environment.IsDevelopment())
    {
        throw new InvalidOperationException("JWT SecretKey is not configured. Set JWT_SETTINGS__SECRET_KEY (preferred) or JwtSettings__SecretKey.");
    }

    wasAutoGenerated = true;
    return Convert.ToBase64String(RandomNumberGenerator.GetBytes(64));
}

static void ValidateJwtSecret(string secret)
{
    if (secret.Length < 32)
    {
        throw new InvalidOperationException("JWT SecretKey must be at least 32 characters long.");
    }
}

public partial class Program
{
}
